src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('personal.urls')),
    path('u/', include(('users.urls', 'users'), namespace='users')),

]

src/personal/urls.py
from django.urls import path
from .views import home_view, details_view, products_view, all_products_view

app_name = 'personal'

urlpatterns = [
    path('', home_view, name='home'),
    path('products/', all_products_view, name='all_products'),
    path('<str:category>/', products_view, name='products'),
    path('product/<str:slug>/', details_view, name='details')
]

src/users/urls.py
from django.urls import path
from .views import registration_view, login_view, logout_view

app_name = 'users'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', registration_view, name='register'),
    path('logout/', logout_view, name='logout'),
]

# TODO: Password Reset

src/personal/models.py
from django.db import models

# Create your models here.
from django.urls import reverse_lazy
from django.utils.text import slugify

AVAILABILITY = [
    ("In Stock", "in-stock"),
    ("Out Of Stock", "out-of-stock")
]


class Category(models.Model):
    name = models.CharField(max_length=100)
    category_slug = models.SlugField(blank=True, unique=True)

    def get_absolute_url(self):
        return reverse_lazy('details', kwargs={'product_category': self.name})

    def save(self, *args, **kwargs):
        value = self.name
        self.category_slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"


class Products(models.Model):
    title = models.CharField(max_length=100)
    imageUrl = models.CharField(max_length=200)
    price = models.CharField(max_length=50)
    description = models.TextField(max_length=500)
    availability = models.CharField(max_length=20, choices=AVAILABILITY)
    slug = models.SlugField(blank=True, unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, to_field='category_slug')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy('details', kwargs={'product_slug': self.slug})

    def save(self, *args, **kwargs):
        value = self.title
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Product"
        verbose_name_plural = "Products"

src/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


# Create your models here.

class MyAccountManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError('Users must have an email address')
        if not username:
            raise ValueError('Users must have a username')

        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        user = self.create_user(
            email=self.normalize_email(email),
            password=password,
            username=username,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class Users(AbstractBaseUser):
    email = models.EmailField(verbose_name="email", max_length=60, unique=True)
    username = models.CharField(max_length=30, unique=True)
    date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'username'  # Field that will be used for login
    REQUIRED_FIELDS = ['email']  # Required field for successful registration

    objects = MyAccountManager()  # Calling MyAccountManager

    def __str__(self):
        return self.email

    # For checking permissions. to keep it simple all admin have ALL permissions
    def has_perm(self, perm, obj=None):
        return self.is_admin

    # Does this user have permission to view this app? (ALWAYS YES FOR SIMPLICITY)
    def has_module_perms(self, app_label):
        return True

src/users/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from .models import Users


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=60, help_text='Required. Add a valid email address')

    class Meta:
        model = Users
        fields = ("email", "username", "password1", "password2")


class UserAuthenticationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = Users
        fields = ('username', 'password')

    def clean(self):
        if self.is_valid():
            username = self.cleaned_data['username']
            password = self.cleaned_data['password']
            if not authenticate(username=username, password=password):
                raise forms.ValidationError("Invalid login")

src/personal/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from .models import Products

context = {}


def home_view(request):
    context['nbar'] = 'home'
    return render(request, "home.html", context)


def all_products_view(request):
    try:
        products = Products.objects.all()
        context['products'] = products
        context['nbar'] = 'products'
        return render(request, "products.html", context)
    except Products.DoesNotExist:
        return render(request, "404.html")


def products_view(request, category):
    products = get_list_or_404(Products, category=category)
    first_product = Products.objects.filter(category=category)[:1].get()
    context['category'] = first_product.category
    context['products'] = products
    context['nbar'] = 'products'
    return render(request, "products.html", context)


def details_view(request, slug):
    product = get_object_or_404(Products, slug=slug)
    context['product'] = product
    context['nbar'] = 'products'
    return render(request, "details.html", context)

src/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from .forms import RegistrationForm, UserAuthenticationForm

context = {}


def registration_view(request):
    if request.POST:
        form = RegistrationForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            user = form.save()
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('personal:home')
        else:
            context['registration_form'] = form  # Read the errors in form
    else:  # GET request; Users will see the registration form at first
        form = RegistrationForm()
        context['registration_form'] = form
        context['nbar'] = 'register'
    return render(request, 'register.html', context)


def logout_view(request):
    logout(request)
    return redirect('personal:home')


def login_view(request):
    user = request.user
    if user.is_authenticated:
        return redirect('personal:home')

    if request.POST:
        form = UserAuthenticationForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)

            if user:
                login(request, user)
                return redirect('personal:home')

    else:
        form = UserAuthenticationForm()

    context['nbar'] = 'login'
    context['login_form'] = form
    return render(request, 'login.html', context)

src/personal/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
      <div class="banner">
        <div class="bnr2">
        </div>
    </div>
    <div class="review">
        <div class="container">
            <h2>{{ category.name }}</h2>

            <div class="review-md1">
                {% for product in products %}
                    <a class="text-center" href="{% url 'personal:details' product.slug %}">
                        <div class="col-md-4 sed-md margin-top-20">
                            <div class=" col-1">
                                <img class="img-responsive center-block" src="{{ product.imageUrl }}" alt="">
                                <h4>{{ product.title }}</h4>
                                <p>{{ product.price }}</p>
                                <p>{{ product.availability }}</p>
                            </div>
                        </div>
                    </a>
                {% endfor %}
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
{% endblock content %}

src/personal/templates/details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="banner">
        <div class="bnr2">
        </div>
    </div>
    <div class="blog">
        <div class="container">
            <div class="col-md-8 blog-left">
                <div class="blog-info">
                    <div class="blog-info-text">
                        <img class="img-responsive zoom-img" src="{{ product.imageUrl }}" alt=""/>
                        <p class="snglp">{{ product.title }}</p>
                        <p class="snglp">{{ product.price }}</p>
                        <p class="snglp">{{ product.availability }}</p>
                        <p class="snglp">{{ product.description }}</p>
                    </div>
                </div>

                <a href="single.html" class="btn btn-primary hvr-rectangle-in">Add To Cart</a>
            </div>
            <div class="col-md-4 single-page-right">

                <div class="recent-posts">
                    <h4>More Products</h4>
                    <div class="recent-posts-info">
                        <div class="posts-left sngl-img">
                            <a href="single.html"> <img src="{% static 'images/img16.jpg' %}"
                                                        class="img-responsive zoom-img" alt=""/>
                            </a>
                        </div>
                        <div class="posts-right">
                            <label>March 5, 2020</label>
                            <h5><a href="single.html">Finibus Bonorum</a></h5>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing incididunt.</p>
                            <a href="single.html" class="btn btn-primary hvr-rectangle-in">Read More</a>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="recent-posts-info">
                        <div class="posts-left sngl-img">
                            <a href="single.html"> <img src="{% static 'images/img17.jpg' %}"
                                                        class="img-responsive zoom-img" alt=""/></a>
                        </div>
                        <div class="posts-right">
                            <label>March 1, 2020</label>
                            <h5><a href="single.html">Finibus Bonorum</a></h5>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing incididunt.</p>
                            <a href="single.html" class="btn btn-primary hvr-rectangle-in">Read More</a>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
{% endblock content %}

src/personal/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <!-- Slider-starts-Here -->
    <script src="{% static 'js/responsiveslides.min.js' %}"></script>
    <script>
        $(function () {
            $("#slider").responsiveSlides({
                auto: true,
                nav: false,
                speed: 500,
                namespace: "callbacks",
                pager: true,
            });
        });

    </script>
    <div class="slider">
        <div class="callbacks_container">
            <ul class="rslides" id="slider">

                <div class="slid banner1">
                    <div class="caption">
                        <h3>Adventure Game - 343 industries - master chief</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec pellentesque ex. Morbi
                            iaculis mi in varius auctor. Nullam feugiat erat ex, eu vehicula velit efficitur non.</p>
                    </div>
                </div>


                <div class="slid banner2">
                    <div class="caption">
                        <h3>God of war - kratos - sony santa monica</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec pellentesque ex. Morbi
                            iaculis mi in varius auctor. Nullam feugiat erat ex, eu vehicula velit efficitur non.</p>
                    </div>
                </div>


                <div class="slid banner3">
                    <div class="caption">
                        <h3>Battlefield 4 - game - explosion - digital illusions</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec pellentesque ex. Morbi
                            iaculis mi in varius auctor. Nullam feugiat erat ex, eu vehicula velit efficitur non.</p>
                    </div>
                </div>

            </ul>
        </div>
    </div>

    <!-- content -->
    <div class="content">
        <div class="container">
            <div class="top-games">
                <h3>Top Products</h3>
                <span></span>
            </div>
            <div class="top-game-grids">
                <ul id="flexiselDemo1">
                    <li>
                        <a href="{% url 'personal:home' %}steam-cards">
                            <div class="game-grid">
                                <h4>Steam Cards</h4>
                                <p></p>
                                <img src="https://durm4gnm0qwu1.cloudfront.net/images/products/156997_1499664889.jpg"
                                     class="img-responsive" alt=""/>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'personal:home' %}psn-cards">
                            <div class="game-grid">
                                <h4>PSN Cards</h4>
                                <p></p>
                                <img src="https://durm4gnm0qwu1.cloudfront.net/images/products/178785_1558062869.jpg?v=1562222092"
                                     class="img-responsive" alt=""/>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'personal:home' %}google-play-cards">
                            <div class="game-grid">
                                <h4>Google Play Gift Cards</h4>
                                <p></p>
                                <img src="https://durm4gnm0qwu1.cloudfront.net/images/products/167071.jpg?v=1561688603"
                                     class="img-responsive" alt=""/>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'personal:home' %}itunes-gift-card">
                            <div class="game-grid">
                                <h4>iTunes Gift Cards</h4>
                                <p></p>
                                <img src="https://durm4gnm0qwu1.cloudfront.net/images/products/172009_1490932145.jpg?v=1555052355"
                                     class="img-responsive" alt=""/>
                            </div>
                        </a>
                    </li>
                </ul>

                <script type="text/javascript">
                    $(window).load(function () {
                        $("#flexiselDemo1").flexisel({
                            visibleItems: 4,
                            animationSpeed: 1000,
                            autoPlay: true,
                            autoPlaySpeed: 3000,
                            pauseOnHover: true,
                            enableResponsiveBreakpoints: true,
                            responsiveBreakpoints: {
                                portrait: {
                                    changePoint: 480,
                                    visibleItems: 1
                                },
                                landscape: {
                                    changePoint: 640,
                                    visibleItems: 2
                                },
                                tablet: {
                                    changePoint: 768,
                                    visibleItems: 3
                                }
                            }
                        });
                    });
                </script>
                <script type="text/javascript" src="{% static 'js/jquery.flexisel.js' %}"></script>
            </div>
        </div>
    </div>
    <!-- latest -->
    <div class="latest">
        <div class="container">
            <div class="latest-games">
                <h3>Latest Games</h3>
                <span></span>
            </div>
            <div class="latest-top">
                <div class="col-md-5 trailer-text">
                    <div class="sub-trailer">
                        <div class="col-md-4 sub-img">
                            <img src="{% static 'images/v2.jpg' %}" alt="img07"/>
                        </div>
                        <div class="col-md-8 sub-text">
                            <a href="#">Killzone: Shadow Fall for PlayStation 4 Reviews</a>
                            <p>Lorem ipsum dolor sit amet, consectetur adipi…</p>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="sub-trailer">
                        <div class="col-md-4 sub-img">
                            <img src="{% static 'images/v1.jpg' %}" alt="img07"/>
                        </div>
                        <div class="col-md-8 sub-text">
                            <a href="#"> Spiderman 2 Full Version PC Game</a>
                            <p>Lorem ipsum dolor sit amet, consectetur adipi…</p>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="sub-trailer">
                        <div class="col-md-4 sub-img">
                            <img src="{% static 'images/v3.jpg' %}" alt="img07"/>
                        </div>
                        <div class="col-md-8 sub-text">
                            <a href="#">Sega's: Jet Set for Andriod Play Store 4 Reviews</a>
                            <p>Lorem ipsum dolor sit amet, consectetur adipi…</p>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="col-md-7 trailer">
                    <iframe src="https://www.youtube.com/embed/V5-DyoVlNOg?list=PLiVunv1pnIs2c0ORVqY60K3n8XMO9CoGp"
                            frameborder="0" allowfullscreen></iframe>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
{% endblock content %}

src/personal/templates/products.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="banner">
        <div class="bnr2">
        </div>
    </div>
    <div class="review">
        <div class="container">
            <h2>Steam Cards</h2>
            {#            <h2>{{ product }}</h2>#}

            <div class="review-md1">
                {% for product in products %}
                    <a class="text-center" href="{% url 'personal:details' product.slug %}">
                        <div class="col-md-4 sed-md margin-top-20">
                            <div class=" col-1">
                                <img class="img-responsive center-block" src="{{ product.imageUrl }}" alt="">
                                <h4>{{ product.title }}</h4>
                                <p>{{ product.price }}</p>
                                <p>{{ product.availability }}</p>
                            </div>
                        </div>
                    </a>
                {% endfor %}
                <div class="clearfix"></div>
            </div>
        </div>
    </div>

{% endblock content %}

src/templates/base.html
{% load static %}
<!DOCTYPE HTML>
<html>
<head>
    <title>Harvest Games Store</title>
    <link href="{% static 'css/bootstrap.css' %}" rel='stylesheet' type='text/css'/>
    <!-- jQuery (necessary JavaScript plugins) -->
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <!-- Custom Theme files -->
    <link href="{% static 'css/custom.css' %}" rel='stylesheet' type='text/css'/>
    <link href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css'/>
    <!-- Custom Theme files -->
    <!--//theme-style-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="keywords" content="Adventure Gaming  Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design"/>
    <script type="application/x-javascript"> addEventListener("load", function () {
        setTimeout(hideURLbar, 0);
    }, false);

    function hideURLbar() {
        window.scrollTo(0, 1);
    } </script>

    <script src="{% static 'js/jquery.min.js' %} "></script>

</head>
<body>
<!-- header -->
<div class="top-banner">
    <div class="header">
        <div class="container">
            <div class="headr-left">
                <div class="social">
                    <a href="https://www.facebook.com/harvestgamesstore/" target="_blank"><i class="facebook"></i></a>
                    <a href="https://www.instagram.com/harvestgamesstore/" target="_blank"><i class="pin"></i></a>
                    <a href="#"><i class="twitter"></i></a>
                </div>
                <div class="search">
                    <form>
                        <input type="submit" value="">
                        <input type="text" value="" placeholder="Search...">
                    </form>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="headr-right">
                <div class="details">
                    <ul>
                        <li><a href="mailto@example.com"><span class="glyphicon glyphicon-envelope"
                                                               aria-hidden="true"></span>info@harvest.com</a></li>
                        <li><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>(+1)226-123-4567</li>
                    </ul>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <!--banner-info-->
    <div class="banner-info">
        <div class="container">
            <div class="logo">
                <h1><a href="{% url 'personal:home' %} ">Harvest Games Store</a></h1>
            </div>
            <div class="top-menu">
                <span class="menu"></span>
                <ul class="nav1">
                    <li class="{% if nbar == 'home' %}active{% endif %}"><a href="{% url 'personal:home' %} ">Home</a></li>
                    <li class="{% if nbar == 'products' %}active{% endif %}"><a href="{% url 'personal:all_products' %}">Products</a></li>
                    {% if request.user.is_authenticated %}
                        <li class="{% if nbar == 'cart' %}active{% endif %}"><a href="#">Cart</a></li>
                        <li class="{% if nbar == 'account' %}active{% endif %}"><a href="#">Account</a></li>
                        <li><a href="{% url 'users:logout' %}">Logout</a></li>
                    {% else %}
                        <li class="{% if nbar == 'login' %}active{% endif %}"><a href="{% url 'users:login' %}">Login</a></li>
                        <li class="{% if nbar == 'register' %}active{% endif %}"><a href="{% url 'users:register' %}">Sign Up</a></li>
                    {% endif %}

                </ul>
            </div>
            <!-- script-for-menu -->
            <script>
                $("span.menu").click(function () {
                    $("ul.nav1").slideToggle(300, function () {
                        // Animation complete.
                    });
                });
            </script>
            <!-- /script-for-menu -->

            <div class="clearfix"></div>
        </div>
    </div>
</div>
{% block content %}
{% endblock content %}
<div class="footer">
    <div class="container">
        <div class="footer-grids">
            <div class="col-md-3 ftr-info">
                <h3>About Us</h3>
                <p>Sed faucibus mollis laoreet. Sed vehicula faucibus tristique lectus a orci molestie finibus.
                    Suspendisse pharetra, metus sed rutrum pretium.</p>
            </div>
            <div class="col-md-3 ftr-grid">
                <h3>Categories</h3>
                <ul class="ftr-list">
                    <li><a href="#">Steam Cards</a></li>
                    <li><a href="#">iTunes Gift Cards</a></li>
                    <li><a href="#">Google Play Cards</a></li>
                    <li><a href="#">PSN Cards</a></li>
                </ul>
            </div>
            <div class="col-md-3 ftr-grid">
                <h3>Platform</h3>
                <ul class="ftr-list">
                    <li><a href="#">Pc</a></li>
                    <li><a href="#">Ps4</a></li>
                    <li><a href="#">XBOX 360</a></li>
                    <li><a href="#">XBOX ONE</a></li>
                    <li><a href="#">PSP</a></li>
                </ul>
            </div>
            <div class="col-md-3 ftr-grid">
                <h3>Information</h3>
                <ul class="ftr-list">
                    <li><a href="#">Contact Us</a></li>
                    <li><a href="#">Terms & Conditions</a></li>
                </ul>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<!---->
<div class="copywrite">
    <div class="container">
        <p> © 2020 Harvest Games Store. All rights reserved</p>
    </div>
</div>
<!---->
</body>
</html>

src/users/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="banner">
        <div class="bnr2">
        </div>
    </div>

    <div class="contact">
        <div class="container">
            <div class="contact-head">
                <h2>Log In</h2>
                <form method="post">
                    {% csrf_token %}
                    <div class="col-md-offset-3 col-md-6 text-center">
                        {% for field in login_form %}
                            <p>{{ field.label_tag }}{{ field }}</p>
                            {% if field.help_text %}
                                <small style="color: grey;">{{ field.help_text }}</small>
                            {% endif %}
                        {% endfor %}

                        {% for field in login_form %}
                            {% for error in field.errors %}
                                <p class="field-error">{{ error }}</p>
                            {% endfor %}
                        {% endfor %}

                        {% if login_form.non_field_errors %}
                            <p class="field-error">{{ login_form.non_field_errors.as_text }}</p>
                        {% endif %}

                        <input type="submit" value="Log in"/>
                    </div>
                    <div class="clearfix"></div>
                </form>
                <p class="col-md-offset-3 col-md-6 text-center margin-top-20"><a href="{% url 'users:register' %}">Create
                    new account</a> | <a href="{% url 'users:register' %}">Forget Password?</a></p>
            </div>

        </div>
    </div>
{% endblock content %}

src/users/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="banner">
        <div class="bnr2">
        </div>
    </div>

    <div class="contact">
        <div class="container">
            <div class="contact-head">
                <h2>Create a new account</h2>
                <form method="post">
                    {% csrf_token %}
                    <div class="col-md-offset-3 col-md-6 text-center">
                        {% for field in registration_form %}
                            <p>
                                {{ field.label_tag }}
                                {{ field }}
                            </p>
                            {% for error in field.errors %}
                                <p class="field-error">{{ error }}</p>
                            {% endfor %}
                        {% endfor %}
                        <input type="submit" value="Sign Up"/>
                    </div>
                    <div class="clearfix"></div>
                </form>
                <p class="col-md-offset-3 col-md-6 text-center margin-top-20"><a href="{% url 'users:login' %}">Already
                    have a account?</a></p>
            </div>
        </div>
    </div>

{% endblock content %}